[book]
authors = ["Qiang Wang"]
language = "en"
src = "docs"
title = "necom Documentation"

[output.html]
git-repository-url = "https://github.com/wang-q/necom"
edit-url-template = "https://github.com/wang-q/necom/edit/master/{path}"
